# Generated by Django 2.2.2 on 2019-06-10 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='link',
            field=models.CharField(default=111, max_length=3000),
            preserve_default=False,
        ),
    ]
