# Generated by Django 2.2.2 on 2019-06-11 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_group_quiz'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='ans1',
            new_name='ansA',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='ans2',
            new_name='ansB',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='ans3',
            new_name='ansC',
        ),
    ]
